### ISSUE TITLE
Odoo API key compatibility 

### ISSUE THREAD

**Issue by simonriskjaer** [tmijail/Odoo-Power-BI-Connector#13]
From Odoo V14 API keys can be used instead of traditional username/pass as auth method. When 2-factor auth is enabled for a user, an authentication error occurs:

![image](https://user-images.githubusercontent.com/12029742/220952279-e6d1b4d2-539f-44c2-a89f-a9037b371a0b.png)

The API key is thus mandatory when using the JsonRPC API with a user that has 2-factor auth enabled. 

Being able to choose authentication method by API key would solve this issue. 

https://www.odoo.com/documentation/16.0/developer/api/external_api.html#api-keys

**Comment by tmijail** [comment]
If I recall correctly, you can just use the API key instead of the password. 

From your link:

> The way to use API Keys in your scripts is to simply replace your password by the key

Could you check?

**Comment by simonriskjaer** [comment]
Yep - that does seem to work just fine.

Thank you for investigating, and sorry for the inconvenience.
