### ISSUE TITLE
Issue with some tables

### ISSUE THREAD

**Issue by NioDigital** [tmijail/Odoo-Power-BI-Connector#9]
Getting error when the tables are opened via get data in PowerBI. Find the screenshot for reference.

![powerbi errors](https://user-images.githubusercontent.com/69922830/181301844-df4e5b64-57fc-498b-98dc-8402e6037e13.png)

**Comment by tmijail** [comment]
What version of Odoo are you using?

**Comment by NioDigital** [comment]
It's Odoo15 enterprise, hosted on Odoo.sh.

**Comment by NioDigital** [comment]
Hi, Did you get any fix?

**Comment by tmijail** [comment]
Fixed en [v0.2.0](https://github.com/tmijail/Odoo-Power-BI-Connector/releases/tag/v0.2.0)
